### ISSUE TITLE
under debian9 compiles after this patch

### ISSUE THREAD

**Issue by grzech0** [NanXiao/tcpbench#1]
diff -ruN tcpbench-master.orig/tcpbench.c tcpbench-master/tcpbench.c
--- tcpbench-master.orig/tcpbench.c	2018-05-14 11:53:16.000000000 +0200
+++ tcpbench-master/tcpbench.c	2018-05-14 20:50:54.480456192 +0200
@@ -19,6 +19,7 @@
 
 #include <sys/types.h>
 #include <sys/time.h>
+#include <time.h>
 #include <sys/socket.h>
 #include <sys/socketvar.h>
 #include <sys/resource.h>

**Comment by NanXiao** [comment]
@grzech0 
Thanks very much for your report! I have updated the code and now the code should work fine on Debian platforms. I will close this issue now. If there are other problems, please reopen it or open new issues, thanks very much again!
